name: CI

# Variables
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

# Triggering the workflow on PRs and pushes to relevant branches
on:
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  # Build and test job
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Installing pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      # Defining what Node.js version to use
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      # Installing node dependencies using pnpm
      - name: Pnpm install
        run: pnpm install --frozen-lockfile
        
      # Linting the application
      - name: Pnpm lint
        run: pnpm lint

      # Persisting Next.js' cache across builds
      - name: Use Next.js cache
        uses: actions/cache@v3.3.2
        with:
          path: ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      # Building the application
      - name: Pnpm build
        run: pnpm build

      # Installing Playwright's browsers
      - name: Install Playwright's browsers
        run: pnpm playwright install --with-deps

      # Running application tests
      - name: Pnpm test
        run: pnpm test

      # Running E2E screenshots check
      - name: E2E check
        run: pnpm e2e-check

      # Committing E2E screenshot changes
      - name: Commit E2E changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "[skip ci] [e2e-check] Automated Playwright E2E screenshot changes commit"
          new_branch: ${{ env.BRANCH_NAME }}
      
      # Running Storybook story screenshots check
      - name: Run stories-check
        run: pnpm stories-check

      # Committing Storybook story screenshot changes
      - name: Commit Storybook changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "[skip ci] [storybook-check] Automated Storybook screenshot changes commit"
          new_branch: ${{ env.BRANCH_NAME }}